## Calculate Covariance Matrix

Write a Python function to calculate the covariance matrix for a given set of vectors. The function should take a list of lists, where each inner list represents a feature with its observations, and return a covariance matrix as a list of lists. Additionally, provide test cases to verify the correctness of your implementation.

In [4]:
data = [[1, 2, 3], [4, 5, 6]]
out = [[1.0, 1.0], [1.0, 1.0]]

In [5]:
rows = len(data)
cols = len(data[0]) if data else 0
shape = (rows, cols)
print("Shape of data:", shape)


Shape of data: (2, 3)


In [6]:
mean = []

for row in data:
    row_mean = sum(row) / len(row)
    mean.append(row_mean)
mean

[2.0, 5.0]

In [7]:
n_features = len(data)
n_observations = len(data[0])

means = [sum(feature) / n_observations for feature in data]

cov_matrix = []


In [8]:
for i in range(n_features):
    row = []
    for j in range(n_features):
        cov = sum(
            (data[i][k] - means[i]) * (data[j][k] - means[j])
            for k in range(n_observations)
        ) / (n_observations - 1)
        row.append(cov)
    cov_matrix.append(row)

In [9]:
cov_matrix

[[1.0, 1.0], [1.0, 1.0]]

## Solve Linear Equations using Jacobi Method

Write a Python function that uses the Jacobi method to solve a system of linear equations given by Ax = b. The function should iterate n times, rounding each intermediate solution to four decimal places, and return the approximate solution x.

In [2]:
A = [[5, -2, 3], [-3, 9, 1], [2, -1, -7]]
b = [-1, 2, 3] 
n=2

In [3]:
Output = [0.146, 0.2032, -0.5175]

In [6]:
import numpy as np

A = np.array(A, dtype=float)
b = np.array(b, dtype=float)

d = len(A)

In [7]:
x = np.zeros(d)

In [8]:
for iteration in range(n):
        x_new = np.zeros(d)
        
        for i in range(d):
            # Calculate sum of off-diagonal terms: sum(a[i,j] * x[j] for j != i)
            off_diagonal_sum = 0
            for j in range(d):
                if i != j:
                    off_diagonal_sum += A[i, j] * x[j]
            
            # Update x[i] using the Jacobi formula
            x_new[i] = (b[i] - off_diagonal_sum) / A[i, i]
        
        # Round to four decimal places
        x_new = np.round(x_new, decimals=4)
        
        # Update x for next iteration
        x = x_new
        
        print(f"Iteration {iteration + 1}: x = {x.tolist()}")
    

Iteration 1: x = [-0.2, 0.2222, -0.4286]
Iteration 2: x = [0.146, 0.2032, -0.5175]


## Singular Value Decomposition (SVD)

Write a Python function called svd_2x2_singular_values(A) that finds an approximate singular value decomposition of a real 2 x 2 matrix using one Jacobi rotation. Input A: a NumPy array of shape (2, 2)

Rules You may use basic NumPy operations (matrix multiplication, transpose, element wise math, etc.). Do not call numpy.linalg.svd or any other high-level SVD routine. Stick to a single Jacobi step no iterative refinements.

Return A tuple (U, Σ, V_T) where U is a 2 x 2 orthogonal matrix, Σ is a length 2 NumPy array containing the singular values, and V_T is the transpose of the right-singular-vector matrix V.

In [4]:
A = [[2, 1], [1, 2]]

In [5]:
print("Output: (array([[-0.70710678, -0.70710678],\n"
      "                [-0.70710678,  0.70710678]]),\n"
      "        array([3., 1.]),\n"
      "        array([[-0.70710678, -0.70710678],\n"
      "               [-0.70710678,  0.70710678]]))")

Output: (array([[-0.70710678, -0.70710678],
                [-0.70710678,  0.70710678]]),
        array([3., 1.]),
        array([[-0.70710678, -0.70710678],
               [-0.70710678,  0.70710678]]))


In [6]:
import numpy as np

A_T = np.transpose(a)

B = np.dot(A_T, A)

B

array([[5, 4],
       [4, 5]])

In [15]:
if B[0,0] == B[1,1]:
    theta = np.pi/4
else:
    theta = np.arctan(2*B[0,1]/(B[0,0]-B[1,1]))/2
theta

# 

0.7853981633974483

In [16]:
R = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])
R

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [12]:
D = R.T @ B @ R
D

array([[9.00000000e+00, 1.11087808e-15],
       [6.36938863e-16, 1.00000000e+00]])

In [20]:
s = np.sqrt([D[0,0], D[1,1]])

In [21]:
V = R
Sigma_inv = np.diag(1/s)
U = A @ V @ Sigma_inv
U
print(U, np.diag(s), V)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] [[3. 0.]
 [0. 1.]] [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [22]:
np.diag(s)

array([[3., 0.],
       [0., 1.]])

## Linear Regression Using Normal Equation

Write a Python function that performs linear regression using the normal equation. The function should take a matrix X (features) and a vector y (target) as input, and return the coefficients of the linear regression model. Round your answer to four decimal places, -0.0 is a valid result for rounding a very small number.

In [24]:
X = [[1, 1], [1, 2], [1, 3]]
y = [1, 2, 3]

In [25]:
Output = [0.0, 1.0]

In [26]:
import numpy as np

X = np.array(X)
y = np.array(y)

coefficients = np.linalg.inv(X.T @ X) @ X.T @ y
coefficients = np.round(coefficients, 4)
coefficients

array([-1.77635684e-15,  1.00000000e+00])

While the normal equation provides an exact solution for linear regression, there are several important reasons why gradient descent is often preferred in practice:

## 1. **Computational Complexity**
- **Normal Equation**: Requires computing `(X^T X)^(-1) X^T y`
- **Matrix Inversion**: O(n³) complexity where n is the number of features
- **Memory Usage**: Needs to store the entire dataset in memory
- **Gradient Descent**: O(n) per iteration, can handle much larger datasets

## 2. **Scalability Issues**
```python
# Normal equation becomes impractical for large datasets
# If you have 100,000 features, you need to invert a 100,000 × 100,000 matrix!
# This would require ~80GB of RAM just for the matrix
```

## 3. **Non-linear Models**
The normal equation only works for **linear regression**. Many real-world problems require:
- **Logistic Regression**: Uses sigmoid function (non-linear)
- **Neural Networks**: Multiple non-linear layers
- **Polynomial Regression**: Higher-degree terms
- **Regularized Models**: L1/L2 penalties

## 4. **Online Learning**
- **Normal Equation**: Requires all data at once (batch learning)
- **Gradient Descent**: Can update parameters with each new data point (online learning)
- **Stochastic GD**: Processes one example at a time

## 5. **Numerical Stability**
```python
# Normal equation can be numerically unstable
# If X^T X is nearly singular (multicollinearity), 
# the inverse becomes unreliable
```

## 6. **Feature Scaling**
- **Normal Equation**: Works regardless of feature scales
- **Gradient Descent**: Requires feature scaling for optimal convergence

## When to Use Each:

**Use Normal Equation when:**
- Small dataset (< 10,000 examples)
- Few features (< 1,000)
- Linear regression only
- Exact solution needed

**Use Gradient Descent when:**
- Large datasets
- Many features
- Non-linear models
- Online learning needed
- Memory constraints


## Linear Regression Using Gradient Descent

Write a Python function that performs linear regression using gradient descent. The function should take NumPy arrays X (features with a column of ones for the intercept) and y (target) as input, along with learning rate alpha and the number of iterations, and return the coefficients of the linear regression model as a NumPy array. Round your answer to four decimal places. -0.0 is a valid result for rounding a very small number.

$$
\theta_j := \theta_j - \alpha \frac{1}{m} \sum_{i=1}^{m} \left( h_\theta(x^{(i)}) - y^{(i)} \right) x_j^{(i)}
$$


In [2]:
import numpy as np
X = np.array([[1, 1], [1, 2], [1, 3]])
y = np.array([1, 2, 3]) 
alpha = 0.01
iterations = 1000

In [3]:
output = np.array([0.1107, 0.9513])

In [4]:


def linear_regression_gd(X, y, alpha, iterations):
    """
    Performs linear regression using gradient descent.

    Parameters:
        X : np.ndarray, shape (m, n)
            Feature matrix with a column of ones for the intercept.
        y : np.ndarray, shape (m,)
            Target vector.
        alpha : float
            Learning rate.
        iterations : int
            Number of iterations.

    Returns:
        theta : np.ndarray
            Coefficients of the linear regression model, rounded to 4 decimals.
    """
    y = np.reshape(y, (-1, 1))
    
    # Get dimensions
    m, n = X.shape
    
    # Initialize parameters
    theta = np.zeros((n, 1))
    
    # Gradient descent
    for _ in range(iterations):
        h = X @ theta  # Hypothesis: X @ theta
        gradient = (1/m) * (X.T @ (h - y))  # Gradient of cost function
        theta = theta - alpha * gradient  # Update parameters
    
    # Return flattened and rounded coefficients
    return np.round(theta.flatten(), 4)



## Feature Scaling Implementation

Write a Python function that performs feature scaling on a dataset using both standardization and min-max normalization. The function should take a 2D NumPy array as input, where each row represents a data sample and each column represents a feature. It should return two 2D NumPy arrays: one scaled by standardization and one by min-max normalization. Make sure all results are rounded to the nearest 4th decimal.

In [5]:
data = np.array([[1, 2], [3, 4], [5, 6]])

output : ([[-1.2247, -1.2247], [0.0, 0.0], [1.2247, 1.2247]], [[0.0, 0.0], [0.5, 0.5], [1.0, 1.0]])

In [10]:
np.std(data, axis=0)

array([1.63299316, 1.63299316])

In [11]:
standardized_data = (data - np.mean(data, axis=0)) / np.std(data, axis=0)
min_max_data = (data - np.min(data, axis=0)) / (np.max(data, axis=0) - np.min(data, axis=0))
print(standardized_data, min_max_data)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]] [[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


## K-Means Clustering

Your task is to write a Python function that implements the k-Means clustering algorithm. This function should take specific inputs and produce a list of final centroids. k-Means clustering is a method used to partition n points into k clusters. The goal is to group similar points together and represent each group by its center (called the centroid).
Function Inputs:

    points: A list of points, where each point is a tuple of coordinates (e.g., (x, y) for 2D points)
    k: An integer representing the number of clusters to form
    initial_centroids: A list of initial centroid points, each a tuple of coordinates
    max_iterations: An integer representing the maximum number of iterations to perform

Function Output:

A list of the final centroids of the clusters, where each centroid is rounded to the nearest fourth decimal.

In [13]:
points = [(1, 2), (1, 4), (1, 0), (10, 2), (10, 4), (10, 0)]
k = 2
initial_centroids = [(1, 1), (10, 1)] 
max_iterations = 10

In [14]:
for _ in range(max_iterations):
    clusters = [[] for _ in range(k)]

clusters

[[], []]

In [16]:
np.linalg.norm(np.array(points[0]) - np.array(initial_centroids[0]))

np.float64(1.0)

In [ ]:
for _ in range(max_iterations):
    clusters = [[] for _ in range(k)]
    for point in points:
        distances = [np.linalg.norm(np.array(point) - np.array(centroid)) for centroid in initial_centroids]
        cluster_index = np.argmin(distances)
        clusters[cluster_index].append(point)
    new_centroids = [np.mean(cluster, axis=0) for cluster in clusters]

## Implement K-Fold Cross-Validation

Implement a function to generate train and test splits for K-Fold Cross-Validation. Your task is to divide the dataset into k folds and return a list of train-test indices for each fold.

In [2]:
import numpy as np
X = np.array([0,1,2,3,4,5,6,7,8,9])
y = np.array([0,1,2,3,4,5,6,7,8,9])
k = 5
shuffle = False


In [3]:
indices = np.arange(len(X))
indices


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
rng = np.random.RandomState(seed= 42)
rng.shuffle(indices)
indices
# We shuffle to ensure that each fold in cross-validation is representative of the overall dataset, preventing bias from any 
# inherent ordering in the data and improving the reliability of model evaluation.

array([8, 1, 5, 0, 7, 2, 9, 4, 3, 6])

In [5]:
fold_sizes = np.full(k, len(X) // k, dtype=int)
fold_sizes

array([2, 2, 2, 2, 2])

In [8]:
fold_sizes[:len(X) % k] += 1
fold_sizes


array([2, 2, 2, 2, 2])

In [7]:
def k_fold_cross_validation(X: np.ndarray, y: np.ndarray, k=5, shuffle=True, random_seed=None):
    
    assert len(X) == len(y)

    n_samples = len(X)
    indices = np.arange(n_samples)

    if shuffle:
        rng = np.random.RandomState(seed= random_seed)
        rng.shuffle(indices)
    
    fold_sizes = np.full(k, n_samples // k, dtype=int)
    fold_sizes[:n_samples % k] += 1

    current_index = 0
    splits = []
    for fold_size in fold_sizes:
        start = current_index
        end = current_index + fold_size
        test_indices = indices[start:end]
        train_indices = np.concatenate((indices[:start], indices[end:]))
        splits.append((train_indices, test_indices))
        current_index = end
        
    return splits


In [8]:
k_fold_cross_validation(np.array([0,1,2,3,4,5,6,7,8,9]), np.array([0,1,2,3,4,5,6,7,8,9]), k=5, shuffle=False)

[(array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1])),
 (array([0, 1, 4, 5, 6, 7, 8, 9]), array([2, 3])),
 (array([0, 1, 2, 3, 6, 7, 8, 9]), array([4, 5])),
 (array([0, 1, 2, 3, 4, 5, 8, 9]), array([6, 7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9]))]

## Principal Component Analysis (PCA) Implementation

Write a Python function that performs Principal Component Analysis (PCA) from scratch. The function should take a 2D NumPy array as input, where each row represents a data sample and each column represents a feature. The function should standardize the dataset, compute the covariance matrix, find the eigenvalues and eigenvectors, and return the principal components (the eigenvectors corresponding to the largest eigenvalues). The function should also take an integer k as input, representing the number of principal components to return.


    1- Standardize the Dataset: Ensure that each feature has a mean of 0 and a standard deviation of 1.
    2- Compute the Covariance Matrix: Reflects how features vary together.
    3- Find Eigenvalues and Eigenvectors: Solve the characteristic equation for the covariance matrix.
    4- Select Principal Components: Choose eigenvectors (components) with the highest eigenvalues for dimensionality reduction.


In [30]:
data = np.array([[1, 2], [3, 4], [5, 6]])
k = 1

In [31]:
mean = np.mean(data, axis=0)
mean

array([3., 4.])

In [32]:
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)
data_centered = (data - mean) / std
cov_matrix = np.cov(data_centered, rowvar=False)
cov_matrix

array([[1.5, 1.5],
       [1.5, 1.5]])

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

top_k_indices = np.argsort(eigenvalues)[::-1][:k]


In [39]:
eigenvectors[:, 0]

array([0.70710678, 0.70710678])

In [ ]:
principal_components = eigenvectors[:, top_k_indices]
principal_components

## Decision Tree Learning 

Write a Python function that implements the decision tree learning algorithm for classification. The function should use recursive binary splitting based on entropy and information gain to build a decision tree. It should take a list of examples (each example is a dict of attribute-value pairs) and a list of attribute names as input, and return a nested dictionary representing the decision tree.

### Process


    1- Select Attribute: Choose the attribute with the highest information gain.
    2- Split Dataset: Divide the dataset based on the values of the selected attribute.
    3- Recursion: Repeat the process for each subset until:
            All data is perfectly classified, or
            No remaining attributes can be used to make a split.

This recursive process continues until the decision tree can no longer be split further or all examples have been classified.

In [6]:
examples = [
                    {'Outlook': 'Sunny', 'Temperature': 'Hot', 'Humidity': 'High', 'Wind': 'Weak', 'PlayTennis': 'No'},
                    {'Outlook': 'Sunny', 'Temperature': 'Hot', 'Humidity': 'High', 'Wind': 'Strong', 'PlayTennis': 'No'},
                    {'Outlook': 'Overcast', 'Temperature': 'Hot', 'Humidity': 'High', 'Wind': 'Weak', 'PlayTennis': 'Yes'},
                    {'Outlook': 'Rain', 'Temperature': 'Mild', 'Humidity': 'High', 'Wind': 'Weak', 'PlayTennis': 'Yes'}
                ]

attributes = ['Outlook', 'Temperature', 'Humidity', 'Wind']
target_attr = 'PlayTennis'

In [7]:
values = [ex[target_attr] for ex in examples]

values

['No', 'No', 'Yes', 'Yes']

In [10]:
import math
from collections import Counter

counts = Counter(values)

for count in counts.values():
    print(count)

2
2


In [15]:
def entropy(examples, target_attr):
    values = [ex[target_attr] for ex in examples]
    total = len(values)
    counts = Counter(values)
    ent = 0.0

    for count in counts.values():
        p = count / total
        if p > 0:
            ent -= p * math.log2(p)
    return ent

In [16]:
entropy(examples, target_attr)

1.0

In [18]:
values = set(ex[attributes[0]] for ex in examples)
values

{'Overcast', 'Rain', 'Sunny'}

In [ ]:
def information_gain(examples, attr, target_attr):
    total_entropy = entropy(examples, target_attr)
    values = set(ex[attr] for ex in examples)
    total = len(examples)
    subset_entropy = 0.0
    for v in values:
        subset = [ex for ex in examples if ex[attr] == v]
        

In [4]:
import math
from collections import Counter

def entropy(examples, target_attr):
    values = [ex[target_attr] for ex in examples]
    total = len(values)
    counts = Counter(values)
    ent = 0.0
    for count in counts.values():
        p = count / total
        if p > 0:
            ent -= p * math.log2(p)
    return ent

def information_gain(examples, attr, target_attr):
    total_entropy = entropy(examples, target_attr)
    values = set(ex[attr] for ex in examples)
    total = len(examples)
    subset_entropy = 0.0
    for v in values:
        subset = [ex for ex in examples if ex[attr] == v]
        weight = len(subset) / total
        subset_entropy += weight * entropy(subset, target_attr)
    return total_entropy - subset_entropy

def majority_value(examples, target_attr):
    values = [ex[target_attr] for ex in examples]
    return Counter(values).most_common(1)[0][0]

def all_same_class(examples, target_attr):
    first = examples[0][target_attr]
    return all(ex[target_attr] == first for ex in examples)

def learn_decision_tree(examples: list[dict], attributes: list[str], target_attr: str) -> dict:
    # Base cases
    if not examples:
        return None
    if all_same_class(examples, target_attr):
        return examples[0][target_attr]
    if not attributes:
        return majority_value(examples, target_attr)

    # Choose best attribute
    gains = [(attr, information_gain(examples, attr, target_attr)) for attr in attributes]
    best_attr = max(gains, key=lambda x: x[1])[0]

    tree = {best_attr: {}}
    attr_values = set(ex[best_attr] for ex in examples)
    for v in attr_values:
        subset = [ex for ex in examples if ex[best_attr] == v]
        if not subset:
            subtree = majority_value(examples, target_attr)
        else:
            remaining_attrs = [a for a in attributes if a != best_attr]
            subtree = learn_decision_tree(subset, remaining_attrs, target_attr)
        tree[best_attr][v] = subtree
    return tree


In [5]:
learn_decision_tree(examples, attributes, 'PlayTennis')

{'Outlook': {'Sunny': 'No', 'Rain': 'Yes', 'Overcast': 'Yes'}}

In [22]:
labels = [ex['Temperature'] for ex in examples]
labels

['Hot', 'Hot', 'Hot', 'Mild']

In [19]:
import math  # 📚 Import the math module for mathematical functions (e.g., log2)
from collections import Counter  # 📊 Import Counter to count occurrences of items
from typing import List, Dict, Any, Union  # 📝 Import type hints for better code clarity

def calculate_entropy(labels: List[Any]) -> float:
    """
    Compute the Shannon entropy of the list of labels.
    Entropy formula: H(S) = -∑ p_i * log2(p_i)
    where p_i is the probability of class i.
    """
    total = len(labels)  # 🔢 Total number of labels (N)
    if total == 0:  # ⚠️ If there are no labels, entropy is 0
        return 0.0
    counts = Counter(labels)  # 🧮 Count occurrences of each label
    entropy = 0.0  # 🏁 Initialize entropy to 0
    for count in counts.values():  # 🔁 For each unique label count
        p = count / total  # 📐 Calculate probability p_i = count / N
        if p > 0:  # 🚦 Only consider non-zero probabilities
            entropy -= p * math.log2(p)  # ➖ Add -p_i * log2(p_i) to entropy (Shannon entropy formula)
    return entropy  # 🎯 Return the computed entropy

def calculate_information_gain(
    examples: List[Dict[str, Any]],
    attr: str,
    target_attr: str
) -> float:
    """
    Compute information gain for splitting `examples` on `attr` w.r.t. `target_attr`.
    Information Gain formula: IG(S, A) = H(S) - ∑_v (|S_v|/|S|) * H(S_v)
    where S is the set of examples, A is the attribute, v are possible values of A,
    and S_v is the subset where A = v.
    """
    total = len(examples)  # 🔢 Total number of examples (|S|)
    if total == 0:  # ⚠️ If no examples, information gain is 0
        return 0.0
    labels = [ex[target_attr] for ex in examples]  # 🏷️ Extract all target labels
    total_entropy = calculate_entropy(labels)  # 🧮 Compute H(S), the entropy before split
    values = set(ex[attr] for ex in examples)  # 🗂️ Get all unique values of attribute A
    subset_entropy = 0.0  # 🏁 Initialize weighted entropy after split
    for v in values:  # 🔁 For each possible value v of attribute A
        subset = [ex for ex in examples if ex[attr] == v]  # 📦 Subset S_v where A = v
        weight = len(subset) / total  # ⚖️ Weight = |S_v| / |S|
        subset_labels = [ex[target_attr] for ex in subset]  # 🏷️ Labels in subset S_v
        subset_entropy += weight * calculate_entropy(subset_labels)  # ➕ Add weighted entropy: (|S_v|/|S|) * H(S_v)
    return total_entropy - subset_entropy  # 🏆 Information gain: IG(S, A) = H(S) - weighted sum

def majority_class(
    examples: List[Dict[str, Any]],
    target_attr: str
) -> Any:
    """
    Return the most common value of `target_attr` in `examples`.
    (Used for majority voting in leaves or when no attributes left)
    """
    labels = [ex[target_attr] for ex in examples]  # 🏷️ Extract all target labels
    if not labels:  # ⚠️ If no labels, return None
        return None
    return Counter(labels).most_common(1)[0][0]  # 🥇 Return the label with highest count

def learn_decision_tree(
    examples: List[Dict[str, Any]],
    attributes: List[str],
    target_attr: str
) -> Union[Dict[str, Any], Any]:
    """
    Learn a decision tree using the ID3 algorithm 🌳.
    Returns either a nested dict representing the tree or a class label at the leaves.
    """
    if not examples:  # 🈳 Base case: if no examples, return None
        return None
    labels = [ex[target_attr] for ex in examples]  # 🏷️ Get all target labels
    if all(label == labels[0] for label in labels):  # ✅ Base case: if all labels are the same, return that label (pure node)
        return labels[0]
    if not attributes:  # 🏁 Base case: if no attributes left, return majority class (majority voting)
        return majority_class(examples, target_attr)
    # 🧮 Compute information gain for each attribute (select best split)
    gains = [(attr, calculate_information_gain(examples, attr, target_attr)) for attr in attributes]
    best_attr = max(gains, key=lambda x: x[1])[0]  # 🥇 Choose attribute with highest information gain
    tree = {best_attr: {}}  # 🌳 Create a new decision node for best_attr
    values = set(ex[best_attr] for ex in examples)  # 🗂️ Get all unique values for best_attr
    for v in values:  # 🔁 For each value v of best_attr
        subset = [ex for ex in examples if ex[best_attr] == v]  # 📦 Subset where best_attr == v
        if not subset:  # 🈳 If subset is empty, use majority class as leaf
            subtree = majority_class(examples, target_attr)
        else:
            remaining_attrs = [a for a in attributes if a != best_attr]  # 📝 Remove best_attr from attribute list
            subtree = learn_decision_tree(subset, remaining_attrs, target_attr)  # 🔄 Recursively build subtree
        tree[best_attr][v] = subtree  # 🌿 Attach subtree to the current node for value v
    return tree  # 🌳 Return the constructed decision tree


In [20]:
learn_decision_tree(examples, attributes, 'PlayTennis')

{'Outlook': {'Sunny': 'No', 'Rain': 'Yes', 'Overcast': 'Yes'}}

## Pegasos Kernel SVM Implementation

Write a Python function that implements a deterministic version of the Pegasos algorithm to train a kernel SVM classifier from scratch. The function should take a dataset (as a 2D NumPy array where each row represents a data sample and each column represents a feature), a label vector (1D NumPy array where each entry corresponds to the label of the sample), and training parameters such as the choice of kernel (linear or RBF), regularization parameter (lambda), and the number of iterations. Note that while the original Pegasos algorithm is stochastic (it selects a single random sample at each step), this problem requires using all samples in every iteration (i.e., no random sampling). The function should perform binary classification and return the model's alpha coefficients and bias.

In [26]:
import numpy as np

data = np.array([[1, 2], [2, 3], [3, 1], [4, 1]]) 
labels = np.array([1, 1, -1, -1]) 
kernel = 'rbf' 
lambda_val = 0.01 
iterations = 100
sigma = 1.0

## **Deterministic Pegasos Algorithm Steps**

**Given:**
- Training samples $(\mathbf{x}_i, y_i)$, with $y_i \in \{-1, 1\}$
- Kernel function $K$
- Regularization parameter $\lambda$
- Total iterations $T$

---

**Algorithm:**

1. **Initialize:**  
   $\alpha_i = 0$ for all $i$, and bias $b = 0$.

2. **For each iteration** $t = 1, 2, \ldots, T$:
    - (a) **Compute learning rate:**  
      $\eta_t = \frac{1}{\lambda t}$
    - (b) **For each training sample** $(\mathbf{x}_i, y_i)$:
        - i. **Compute decision value:**  
          $f(\mathbf{x}_i) = \sum_j \alpha_j y_j K(\mathbf{x}_j, \mathbf{x}_i) + b$
        - ii. **If margin constraint is violated** ($y_i f(\mathbf{x}_i) < 1$), **update:**
            - $\alpha_i \leftarrow \alpha_i + \eta_t (y_i - \lambda \alpha_i)$
            - $b \leftarrow b + \eta_t y_i$

---

**Common kernel functions:**

- **Linear kernel:**  
  $K(\mathbf{x}, \mathbf{y}) = \mathbf{x} \cdot \mathbf{y}$

- **Radial Basis Function (RBF) kernel:**  
  $K(\mathbf{x}, \mathbf{y}) = \exp\left(-\frac{\|\mathbf{x} - \mathbf{y}\|^2}{2\sigma^2}\right)$


In [31]:
def kernel_function(x, y, kernel='linear', sigma=1.0):
    if kernel == 'linear':
        return np.dot(x, y)
    elif kernel == 'rbf':
        return np.exp(-np.linalg.norm(x - y) ** 2 / (2 * sigma ** 2))
    else:
        raise ValueError(f"Unsupported kernel: {kernel}")

def pegasos_kernel_svm(data: np.ndarray, labels: np.ndarray, kernel='linear', lambda_val=0.01, iterations=100, sigma=1.0) -> (list, float):
    n_samples = len(data)
    alphas = [0.0] * n_samples
    b = 0.0

    for t in range(1, iterations + 1):
        eta_t = 1 / (lambda_val * t)
        for i in range(n_samples):
            x_i = data[i]
            y_i = labels[i]
            # Use the correct kernel function
            def kf(x, y):
                return kernel_function(x, y, kernel=kernel, sigma=sigma)
            # Compute decision value
            decision_value = sum(alphas[j] * labels[j] * kf(data[j], x_i) for j in range(n_samples)) + b
            if y_i * decision_value < 1:
                # Update alpha_i and b as per the deterministic Pegasos update
                alphas[i] += eta_t * (y_i - lambda_val * alphas[i])
                b += eta_t * y_i
            # No else branch: only update when margin is violated

    # For output formatting, round b to 4 decimals as in the expected output
    b = round(b, 4)
    # If all alphas are integer-valued, cast to int for output
    alphas_out = [float(a) if abs(a - int(a)) > 1e-8 else int(a) for a in alphas]
    return alphas_out, b

## Sigmoid Activation Function Understanding

Write a Python function that computes the output of the sigmoid activation function given an input value z. The function should return the output rounded to four decimal places.

In [1]:
z = 0

In [ ]:
import math
def sigmoid(z: float) -> float:
    result = 1 / (1 + math.exp(-z))
    result = round(result, 4)
    return result

sigmoid(z)




np.float64(0.5)

## Softmax Activation Function Implementation 

Write a Python function that computes the softmax activation for a given list of scores. The function should return the softmax values as a list, each rounded to four decimal places.

In [4]:
scores = [1, 2, 3]

In [8]:
import math

def softmax(scores: list[float]) -> list[float]:
	# Your code here

    probabilities = []

    sum_exp = sum(math.exp(score) for score in scores)

    for z in scores:
        softmax = math.exp(z) / sum_exp
        softmax = round(softmax, 4)
        probabilities.append(softmax) 
    
    return probabilities

## Single Neuron

Write a Python function that simulates a single neuron with a sigmoid activation function for binary classification, handling multidimensional input features. The function should take a list of feature vectors (each vector representing multiple features for an example), associated true binary labels, and the neuron's weights (one for each feature) and bias as input. It should return the predicted probabilities after sigmoid activation and the mean squared error between the predicted probabilities and the true labels, both rounded to four decimal places.

In [21]:
features = [[0.5, 1.0], [-1.5, -2.0], [2.0, 1.5]] 
labels = [0, 1, 0] 
weights = [0.7, -0.4] 
bias = -0.1

In [12]:
sum(w * x for w, x in zip(weights, features[0]))


-0.050000000000000044

In [23]:
import math 

def single_neuron_model(features: list[list[float]], labels: list[int], weights: list[float], bias: float) -> (list[float], float):
	# Your code here
	probabilities = []
	mse = 0
	for feature, label in zip(features, labels):
		z = sum(w * x for w, x in zip(weights, feature)) + bias
		sigmoid = 1 / (1 + math.exp(-z))
		probabilities.append(sigmoid)
		mse += (sigmoid - label) ** 2
	mse = mse / len(features)
	return probabilities, mse

## Single Neuron with Backpropagation

Write a Python function that simulates a single neuron with sigmoid activation, and implements backpropagation to update the neuron's weights and bias. The function should take a list of feature vectors, associated true binary labels, initial weights, initial bias, a learning rate, and the number of epochs. The function should update the weights and bias using gradient descent based on the MSE loss, and return the updated weights, bias, and a list of MSE values for each epoch, each rounded to four decimal places.

# Neural Network Learning with Backpropagation

This task involves implementing backpropagation for a single neuron in a neural network. The neuron processes inputs and updates its parameters to minimize the Mean Squared Error (MSE) between predicted outputs and true labels.

## Mathematical Background

### Forward Pass

Compute the neuron's output by calculating the dot product of the weights and input features, then adding the bias:

$$
z = w_1 x_1 + w_2 x_2 + \cdots + w_n x_n + b
$$

Apply the sigmoid activation function:

$$
\sigma(z) = \frac{1}{1 + e^{-z}}
$$

### Loss Calculation (MSE)

The Mean Squared Error quantifies the error between the neuron's predictions and the actual labels:

$$
\text{MSE} = \frac{1}{n} \sum_{i=1}^{n} (\sigma(z_i) - y_i)^2
$$

### Backward Pass (Gradient Calculation)

Compute the gradient of the MSE with respect to each weight and the bias. This involves the partial derivatives of the loss function with respect to the neuron's output, multiplied by the derivative of the sigmoid function:

$$
\frac{\partial \text{MSE}}{\partial w_j} = \frac{2}{n} \sum_{i=1}^{n} (\sigma(z_i) - y_i) \cdot \sigma'(z_i) \cdot x_{ij}
$$

$$
\frac{\partial \text{MSE}}{\partial b} = \frac{2}{n} \sum_{i=1}^{n} (\sigma(z_i) - y_i) \cdot \sigma'(z_i)
$$

where $\sigma'(z) = \sigma(z) \cdot (1 - \sigma(z))$.

### Parameter Update

Update each weight and the bias by subtracting a portion of the gradient, determined by the learning rate $\alpha$:

$$
w_j = w_j - \alpha \frac{\partial \text{MSE}}{\partial w_j}
$$

$$
b = b - \alpha \frac{\partial \text{MSE}}{\partial b}
$$

## Practical Implementation

This process refines the neuron's ability to predict accurately by iteratively adjusting the weights and bias based on the error gradients, optimizing the neural network's performance over multiple iterations (epochs).


In [25]:
features = [[1.0, 2.0], [2.0, 1.0], [-1.0, -2.0]]
labels = [1, 0, 0]
initial_weights = [0.1, -0.2]
initial_bias = 0.0
learning_rate = 0.1
epochs = 2

In [26]:
import numpy as np
def train_neuron(features: np.ndarray, labels: np.ndarray, initial_weights: np.ndarray, initial_bias: float, learning_rate: float, epochs: int) -> (np.ndarray, float, list[float]):
	# Your code here
	weights = initial_weights.copy()
	bias = initial_bias
	mse_values = []
	n_samples = features.shape[0]

	for epoch in range(epochs):
		z = np.dot(features, weights) + bias
		sigmoid = 1 / (1 + np.exp(-z))
		errors = sigmoid - labels
		mse = np.mean(errors ** 2)
		mse_values.append(mse)

		# Gradients
		sigmoid_deriv = sigmoid * (1 - sigmoid)
		grad_w = (2 / n_samples) * np.dot((errors * sigmoid_deriv), features)
		grad_b = (2 / n_samples) * np.sum(errors * sigmoid_deriv)

		# Update
		weights = weights - learning_rate * grad_w
		bias = bias - learning_rate * grad_b

	updated_weights = weights
	updated_bias = bias
	return updated_weights, updated_bias, mse_values