## Calculate Covariance Matrix

Write a Python function to calculate the covariance matrix for a given set of vectors. The function should take a list of lists, where each inner list represents a feature with its observations, and return a covariance matrix as a list of lists. Additionally, provide test cases to verify the correctness of your implementation.

In [4]:
data = [[1, 2, 3], [4, 5, 6]]
out = [[1.0, 1.0], [1.0, 1.0]]

In [5]:
rows = len(data)
cols = len(data[0]) if data else 0
shape = (rows, cols)
print("Shape of data:", shape)


Shape of data: (2, 3)


In [6]:
mean = []

for row in data:
    row_mean = sum(row) / len(row)
    mean.append(row_mean)
mean

[2.0, 5.0]

In [7]:
n_features = len(data)
n_observations = len(data[0])

means = [sum(feature) / n_observations for feature in data]

cov_matrix = []


In [8]:
for i in range(n_features):
    row = []
    for j in range(n_features):
        cov = sum(
            (data[i][k] - means[i]) * (data[j][k] - means[j])
            for k in range(n_observations)
        ) / (n_observations - 1)
        row.append(cov)
    cov_matrix.append(row)

In [9]:
cov_matrix

[[1.0, 1.0], [1.0, 1.0]]

## Solve Linear Equations using Jacobi Method

Write a Python function that uses the Jacobi method to solve a system of linear equations given by Ax = b. The function should iterate n times, rounding each intermediate solution to four decimal places, and return the approximate solution x.

In [2]:
A = [[5, -2, 3], [-3, 9, 1], [2, -1, -7]]
b = [-1, 2, 3] 
n=2

In [3]:
Output = [0.146, 0.2032, -0.5175]

In [6]:
import numpy as np

A = np.array(A, dtype=float)
b = np.array(b, dtype=float)

d = len(A)

In [7]:
x = np.zeros(d)

In [8]:
for iteration in range(n):
        x_new = np.zeros(d)
        
        for i in range(d):
            # Calculate sum of off-diagonal terms: sum(a[i,j] * x[j] for j != i)
            off_diagonal_sum = 0
            for j in range(d):
                if i != j:
                    off_diagonal_sum += A[i, j] * x[j]
            
            # Update x[i] using the Jacobi formula
            x_new[i] = (b[i] - off_diagonal_sum) / A[i, i]
        
        # Round to four decimal places
        x_new = np.round(x_new, decimals=4)
        
        # Update x for next iteration
        x = x_new
        
        print(f"Iteration {iteration + 1}: x = {x.tolist()}")
    

Iteration 1: x = [-0.2, 0.2222, -0.4286]
Iteration 2: x = [0.146, 0.2032, -0.5175]


## Singular Value Decomposition (SVD)

Write a Python function called svd_2x2_singular_values(A) that finds an approximate singular value decomposition of a real 2 x 2 matrix using one Jacobi rotation. Input A: a NumPy array of shape (2, 2)

Rules You may use basic NumPy operations (matrix multiplication, transpose, element wise math, etc.). Do not call numpy.linalg.svd or any other high-level SVD routine. Stick to a single Jacobi step no iterative refinements.

Return A tuple (U, Σ, V_T) where U is a 2 x 2 orthogonal matrix, Σ is a length 2 NumPy array containing the singular values, and V_T is the transpose of the right-singular-vector matrix V.

In [4]:
A = [[2, 1], [1, 2]]

In [5]:
print("Output: (array([[-0.70710678, -0.70710678],\n"
      "                [-0.70710678,  0.70710678]]),\n"
      "        array([3., 1.]),\n"
      "        array([[-0.70710678, -0.70710678],\n"
      "               [-0.70710678,  0.70710678]]))")

Output: (array([[-0.70710678, -0.70710678],
                [-0.70710678,  0.70710678]]),
        array([3., 1.]),
        array([[-0.70710678, -0.70710678],
               [-0.70710678,  0.70710678]]))


In [6]:
import numpy as np

A_T = np.transpose(a)

B = np.dot(A_T, A)

B

array([[5, 4],
       [4, 5]])

In [15]:
if B[0,0] == B[1,1]:
    theta = np.pi/4
else:
    theta = np.arctan(2*B[0,1]/(B[0,0]-B[1,1]))/2
theta

# 

0.7853981633974483

In [16]:
R = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])
R

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [12]:
D = R.T @ B @ R
D

array([[9.00000000e+00, 1.11087808e-15],
       [6.36938863e-16, 1.00000000e+00]])

In [20]:
s = np.sqrt([D[0,0], D[1,1]])

In [21]:
V = R
Sigma_inv = np.diag(1/s)
U = A @ V @ Sigma_inv
U
print(U, np.diag(s), V)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] [[3. 0.]
 [0. 1.]] [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [22]:
np.diag(s)

array([[3., 0.],
       [0., 1.]])

## Linear Regression Using Normal Equation

Write a Python function that performs linear regression using the normal equation. The function should take a matrix X (features) and a vector y (target) as input, and return the coefficients of the linear regression model. Round your answer to four decimal places, -0.0 is a valid result for rounding a very small number.

In [24]:
X = [[1, 1], [1, 2], [1, 3]]
y = [1, 2, 3]

In [25]:
Output = [0.0, 1.0]

In [26]:
import numpy as np

X = np.array(X)
y = np.array(y)

coefficients = np.linalg.inv(X.T @ X) @ X.T @ y
coefficients = np.round(coefficients, 4)
coefficients

array([-1.77635684e-15,  1.00000000e+00])

While the normal equation provides an exact solution for linear regression, there are several important reasons why gradient descent is often preferred in practice:

## 1. **Computational Complexity**
- **Normal Equation**: Requires computing `(X^T X)^(-1) X^T y`
- **Matrix Inversion**: O(n³) complexity where n is the number of features
- **Memory Usage**: Needs to store the entire dataset in memory
- **Gradient Descent**: O(n) per iteration, can handle much larger datasets

## 2. **Scalability Issues**
```python
# Normal equation becomes impractical for large datasets
# If you have 100,000 features, you need to invert a 100,000 × 100,000 matrix!
# This would require ~80GB of RAM just for the matrix
```

## 3. **Non-linear Models**
The normal equation only works for **linear regression**. Many real-world problems require:
- **Logistic Regression**: Uses sigmoid function (non-linear)
- **Neural Networks**: Multiple non-linear layers
- **Polynomial Regression**: Higher-degree terms
- **Regularized Models**: L1/L2 penalties

## 4. **Online Learning**
- **Normal Equation**: Requires all data at once (batch learning)
- **Gradient Descent**: Can update parameters with each new data point (online learning)
- **Stochastic GD**: Processes one example at a time

## 5. **Numerical Stability**
```python
# Normal equation can be numerically unstable
# If X^T X is nearly singular (multicollinearity), 
# the inverse becomes unreliable
```

## 6. **Feature Scaling**
- **Normal Equation**: Works regardless of feature scales
- **Gradient Descent**: Requires feature scaling for optimal convergence

## When to Use Each:

**Use Normal Equation when:**
- Small dataset (< 10,000 examples)
- Few features (< 1,000)
- Linear regression only
- Exact solution needed

**Use Gradient Descent when:**
- Large datasets
- Many features
- Non-linear models
- Online learning needed
- Memory constraints


## Linear Regression Using Gradient Descent

Write a Python function that performs linear regression using gradient descent. The function should take NumPy arrays X (features with a column of ones for the intercept) and y (target) as input, along with learning rate alpha and the number of iterations, and return the coefficients of the linear regression model as a NumPy array. Round your answer to four decimal places. -0.0 is a valid result for rounding a very small number.

$$
\theta_j := \theta_j - \alpha \frac{1}{m} \sum_{i=1}^{m} \left( h_\theta(x^{(i)}) - y^{(i)} \right) x_j^{(i)}
$$


In [27]:
X = np.array([[1, 1], [1, 2], [1, 3]])
y = np.array([1, 2, 3]) 
alpha = 0.01
iterations = 1000

In [28]:
output = np.array([0.1107, 0.9513])

In [29]:


def linear_regression_gd(X, y, alpha, iterations):
    """
    Performs linear regression using gradient descent.

    Parameters:
        X : np.ndarray, shape (m, n)
            Feature matrix with a column of ones for the intercept.
        y : np.ndarray, shape (m,)
            Target vector.
        alpha : float
            Learning rate.
        iterations : int
            Number of iterations.

    Returns:
        theta : np.ndarray
            Coefficients of the linear regression model, rounded to 4 decimals.
    """
    y = np.reshape(y, (-1, 1))
    
    # Get dimensions
    m, n = X.shape
    
    # Initialize parameters
    theta = np.zeros((n, 1))
    
    # Gradient descent
    for _ in range(iterations):
        h = X @ theta  # Hypothesis: X @ theta
        gradient = (1/m) * (X.T @ (h - y))  # Gradient of cost function
        theta = theta - alpha * gradient  # Update parameters
    
    # Return flattened and rounded coefficients
    return np.round(theta.flatten(), 4)

